version: 2.1

jobs:
  prep_host:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run:
          command: |
            echo ${PWD}
            ls -la .

workflows:
  cdms:
    jobs:
      - prep_host:
          matrix:
            parameters:
              os: [ linux, macos ]
          name: os-<< matrix.os >>
