version: 2.1

executors:
  linux:
    machine:
      image: circleci/classic:latest
  macos:
    macos:
      xcode: "11.4.0"

jobs:
  build:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - attach_workspace:
          at: .
      - checkout:
          path: cdms
      - run:
          command: |
            export WORK_DIR=`pwd ${CIRCLE_WORKING_DIRECTORY}`

            cd cdms/

            make build

            mkdir -p build_artificats

            cp conda-bld/**/*.tar.bz2 build_artifacts/
      - persist_to_workspace:
          root: .
          paths:
            - cdms
            - miniconda
            - pkgs
            - conda-bld
            - build_artifacts
  test:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    environment:
      OS: << parameters.os >>
    steps:
      - attach_workspace:
          at: .
      - run:
          command: |
            export WORK_DIR=`pwd ${CIRCLE_WORKING_DIRECTORY}`

            cd cdms/

            make test

            mkdir -p test_artifacts/`make list-config`

            cp -rf  tests_html/* test_artifacts/`make list-config`
      - persist_to_workspace:
          root: .
          paths:
            - build_artifacts
            - test_artifacts

  upload:
    machine:
      image: circleci/classic:latest
    steps:
      - attach_workspace:
          at: .
      - run: ls -la build_artifacts/
      - run: ls -la test_artifacts/

workflows:
  cdms:
    jobs:
      - build:
          matrix:
            parameters:
              os: [ linux, macos ]
          name: build-<< matrix.os >>
      - test:
          matrix:
            parameters:
              os: [ linux, macos ]
          name: test-<<matrix.os>>
          requires:
            - build-<< matrix.os >>
      - upload:
          name: upload
          requires:
            - test
