version: 2.1

aliases:
  - &setup_miniconda
    name: setup_miniconda
    command: |
      CIRCLE_WORKING_DIRECTORY=`pwd ${CIRCLE_WORKING_DIRECTORY}`
      MINICONDA_DIR=${CIRCLE_WORKING_DIRECTORY}/miniconda

      echo "MINICONDA_DIR ${MINICONDA_DIR}"

      if [[ `uname` == "Darwin" ]]
      then
        curl -L -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
      else
        curl -L -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
      fi

      chmod +x miniconda.sh
      ./miniconda.sh -b -u -p ${MINICONDA_DIR}

      source ${MINICONDA_DIR}/etc/profile.d/conda.sh

      conda activate base
      
      conda info

  - &build
    name: build
    command: |
      source ${MINICONDA_DIR}/etc/profile.d/conda.sh

      conda activate base

      conda info

executors:
  linux:
    machine:
      image: circleci/classic:latest
  macos:
    macos:
      xcode: "11.4.0"

jobs:
  prep_host:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - attach_workspace:
          at: .
      - checkout:
          path: cdms
      - restore_cache:
          key: conda-{{ arch }}
      - run: *setup_miniconda
      - save_cache:
          key: conda-{{ arch }}
          paths:
            - miniconda
      - persist_to_workspace:
          root: .
          paths:
            - miniconda
            - cdms
  build:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - attach_workspace:
          at: .
      - run: *build

workflows:
  cdms:
    jobs:
      - prep_host:
          matrix:
            parameters:
              os: [ linux, macos ]
          name: prep-host-<< matrix.os >>
      - build:
          matrix:
            parameters:
              os: [ linux, macos ]
          name: build-<< matrix.os >>
          requires:
            - prep-host-<< matrix.os >>
