version: 2.1

executors:
  linux:
    machine:
      image: circleci/classic:latest
  macos:
    macos:
      xcode: "11.4.0"

jobs:
  build:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - attach_workspace:
          at: .
      - checkout:
          path: cdms
      - run:
          command: |
            [[ `uname` == "Darwin" ]] && ARCH=osx-64 || ARCH=linux-64

            export WORK_DIR=`pwd ${CIRCLE_WORKING_DIRECTORY}`
            export ARTIFACT_DIR=${WORK_DIR}/build_artifacts/${ARCH}

            pushd cdms/
            make build
            popd

            mkdir -p ${ARTIFACT_DIR}

            cp ${WORK_DIR}/conda-bld/${ARCH}/*.tar.bz2 ${ARTIFACT_DIR}
      - run: date +%Y%m > date
      - persist_to_workspace:
          root: .
          paths:
            - build_artifacts
      - save_cache:
          paths:
            - miniconda
            - pkgs
          key: conda-pkgs-{{ arch }}-{{ checksum "date" }}
  test:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - attach_workspace:
          at: .
      - run: date +%Y%m > date
      - restore_cache:
          key: conda-pkgs-{{ arch }}-{{ checksum "date" }}
      - checkout:
          path: cdms
      - run:
          command: |
            export WORK_DIR=`pwd ${CIRCLE_WORKING_DIRECTORY}`

            cp -rf ${WORK_DIR}/build_artifacts ${WORK_DIR}/local_conda_channel
            source ${WORK_DIR}/miniconda/etc/profile.d/conda.sh
            conda activate base
            conda install -c conda-forge conda-build --yes
            conda index ${WORK_DIR}/local_conda_channel

            cd cdms/

            make test LOCAL_CONDA_CHANNEL=${WORK_DIR}/local_conda_channel

            mkdir -p test_results/
            mv tests_html test_results/`make list-config`
      - store_artifacts:
          path: test_results/
          destination: test_results/
      - save_cache:
          paths:
            - miniconda
            - pkgs
          key: conda-pkgs-{{ arch }}-{{ checksum "date" }}

  upload:
    machine:
      image: circleci/classic:latest
    steps:
      - attach_workspace:
          at: .
      - run: ls -la build_artifacts/

workflows:
  cdms:
    jobs:
      - build:
          matrix:
            parameters:
              os: [ linux, macos ]
          name: build-<< matrix.os >>
      - test:
          matrix:
            parameters:
              os: [ linux, macos ]
          name: test-<<matrix.os>>
          requires:
            - build-<< matrix.os >>
      - upload:
          name: upload
          requires:
            - test
