version: 2.1

executors:
  linux:
    machine:
      image: circleci/classic:latest
  macos:
    macos:
      xcode: "11.4.0"

jobs:
  prep_host:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout:
          path: cdms
      - run:
          command: |
            pwd

            echo `uname` >> test_os

            ls -la .

            cd cdms
            make list-configs SHELL="sh -x"
      - persist_to_workspace:
          root: .
          paths:
            - "."

  build:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - attach_workspace:
          at: .
      - run:
          command: |
            pwd
            
            ls -la .

            cat test_os

workflows:
  cdms:
    jobs:
      - prep_host:
          matrix:
            parameters:
              os: [ linux, macos ]
          name: prep-host-<< matrix.os >>
      - build:
          matrix:
            parameters:
              os: [ linux, macos ]
          name: build-<< matrix.os >>
          requires:
            - prep-host-<< matrix.os >>
