version: 2.1

aliases:
  - &setup_miniconda
    name: setup_miniconda
    command: |
      if [[ `uname` == "Darwin" ]]
      then
        curl -L -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
      else
        curl -L -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
      fi

      ./miniconda.sh -b -p ${CIRCLE_WORKING_DIRECTORY}/miniconda

executors:
  linux:
    machine:
      image: circleci/classic:latest
  macos:
    macos:
      xcode: "11.4.0"

jobs:
  prep_host:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: *setup_miniconda
      - run:
          command: |
            echo ${PWD}
            ls -la .

workflows:
  cdms:
    jobs:
      - prep_host:
          matrix:
            parameters:
              os: [ linux, macos ]
          name: os-<< matrix.os >>
