version: 2

aliases:
  - &setup_miniconda
    name: setup_miniconda
    command: |
       mkdir -p workspace
       git clone -b validateNightly git@github.com:CDAT/cdat workspace/cdat
       # install_miniconda.py installs miniconda3 under $WORKDIR/miniconda
       python workspace/cdat/scripts/install_miniconda.py -w $WORKDIR -p 'py3'

  - &build_cdms
    name: build_cdms
    command: |
       git clone -b sync_recipe_TMP https://github.com/CDAT/conda-recipes.git $WORKDIR/conda-recipes 
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       python $WORKDIR/conda-recipes/build_tools/conda_build_upload.py -w $WORKDIR -l $LAST_STABLE -B 0 -p cdms2 -r cdms -b $CIRCLE_BRANCH

  - &setup_run_tests
    name: setup_run_tests
    environment:
       PKGS: "testsrunner myproxyclient cdms2"
       CHANNELS: "-c cdat/label/linatest -c cdat/label/nightly -c conda-forge"
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       conda config --add channels cdat/label/linatest --force
       conda config --add channels cdat/label/nightly --force
       conda config --set channel_priority false
       conda create -y -n test_cdms --use-local $CHANNELS "$PY_VER" $PKGS
       conda activate test_cdms
       conda list
       echo "python -c 'import cdms2'"
       python -c "import cdms2"

  - &run_tests
    name: run_tests
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       # conda activate base
       conda activate test_cdms
       echo "python -c 'import cdms2'"
       python -c "import cdms2; import sys; print(sys.path)"
       python run_tests.py -H -v2 --subdir

jobs:
   linux_cdms_py37:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: "/home/circleci/project/workdir"
         LAST_STABLE: "3.1.4"
         PY_VER: "python>=3.7,<3.8"
      steps:
         - checkout
         - run: *setup_miniconda
         - run: *build_cdms
         - run: *setup_run_tests
         - run: *run_tests

workflows:
   version: 2
   cdms:
      jobs:
         - linux_cdms_py37
