version: 2.1

executors:
  linux:
    machine:
      image: circleci/classic:latest
  macos:
    macos:
      xcode: "11.4.0"

jobs:
  build:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - attach_workspace:
          at: .
      - checkout:
          path: cdms
      - run:
          command: |
            export CIRCLE_WORKING_DIRECTORY=`pwd ${CIRCLE_WORKING_DIRECTORY}`
            export WORK_DIR=${CIRCLE_WORKING_DIRECTORY}

            cd cdms/

            make build

            rm -rf ${WORKDIR}/miniconda/envs/build
      - persist_to_workspace:
          root: .
          paths:
            - cdms
            - miniconda
            - feedstock
  test:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - attach_workspace:
          at: .
      - run:
          command: |
            export CIRCLE_WORKING_DIRECTORY=`pwd ${CIRCLE_WORKING_DIRECTORY}`
            export WORK_DIR=${CIRCLE_WORKING_DIRECTORY}

            cd cdms/

            make test

            rm -rf ${WORK_DIR}/miniconda/envs/test
      - persist_to_workspace:
          root: .
          paths:
            - miniconda

  upload:
    machine:
      image: circleci/classic:latest
    steps:
      - attach_workspace:
          at: .
      - run: ls -la miniconda/envs/build/conda-bld/linux-64
      - run: ls -la miniconda/envs/build/conda-bld/osx-64

workflows:
  cdms:
    jobs:
      - build:
          matrix:
            parameters:
              os: [ linux, macos ]
          name: build-<< matrix.os >>
      - test:
          matrix:
            parameters:
              os: [ linux, macos ]
          name: test-<<matrix.os>>
          requires:
            - build-<< matrix.os >>
      - upload:
          name: upload
          requires:
            - test
