version: 2.1

aliases:
  - &setup_env
    name: setup_env
    command: | 
      echo "export CIRCLE_WORKING_DIRECTORY=`pwd ${CIRCLE_WORKING_DIRECTORY}`" >> ${BASH_ENV}
      echo "export MINICONDA_DIR=${CIRCLE_WORKING_DIRECTORY}/miniconda" >> ${BASH_ENV}

executors:
  linux:
    machine:
      image: circleci/classic:latest
  macos:
    macos:
      xcode: "11.4.0"

jobs:
  prep_host:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - attach_workspace:
          at: .
      - checkout:
          path: cdms
      - restore_cache:
          key: conda-{{ arch }}-1
      - run:
          command: |
            export CIRCLE_WORKING_DIRECTORY=`pwd ${CIRCLE_WORKING_DIRECTORY}`
            export MINICONDA_DIR=${CIRCLE_WORKING_DIRECTORY}/miniconda

            echo "MINICONDA_DIR ${MINICONDA_DIR}"

            if [[ `uname` == "Darwin" ]]
            then
              curl -L -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
            else
              curl -L -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
            fi

            chmod +x miniconda.sh
            ./miniconda.sh -b -u -p ${MINICONDA_DIR}

            source ${MINICONDA_DIR}/etc/profile.d/conda.sh

            conda activate base

            conda config --system --remove-key pkgs_dirs || true
            conda config --system --append pkgs_dirs ${CIRCLE_WORKING_DIRECTORY}/conda_pkgs
            
            conda info

            conda update -n base conda
      - save_cache:
          key: conda-{{ arch }}-1
          paths:
            - conda_pkgs
      - persist_to_workspace:
          root: .
          paths:
            - conda_pkgs
            - miniconda
            - cdms
  build:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - attach_workspace:
          at: .
      - run:
          command: |
            export CIRCLE_WORKING_DIRECTORY=`pwd ${CIRCLE_WORKING_DIRECTORY}`
            export MINICONDA_DIR=${CIRCLE_WORKING_DIRECTORY}/miniconda
            export WORK_DIR=${CIRCLE_WORKING_DIRECTORY}

            source ${MINICONDA_DIR}/etc/profile.d/conda.sh

            conda activate base

            conda info

            cd cdms

            ls -la ../feedstock/.ci_support/

            make list-configs
            make build

workflows:
  cdms:
    jobs:
      - prep_host:
          matrix:
            parameters:
              os: [ linux, macos ]
          name: prep-host-<< matrix.os >>
      - build:
          matrix:
            parameters:
              os: [ linux, macos ]
          name: build-<< matrix.os >>
          requires:
            - prep-host-<< matrix.os >>
