version: 2

aliases:
  - &setup_miniconda
    name: setup_miniconda
    command: |
       mkdir -p workspace
       git clone -b validateNightly git@github.com:CDAT/cdat workspace/cdat
       # install_miniconda.py installs miniconda3 under $WORKDIR/miniconda
       python workspace/cdat/scripts/install_miniconda.py -w $WORKDIR -p 'py3'

  - &build_cdms
    name: build_cdms
    command: |
       git clone -b sync_recipe https://github.com/CDAT/conda-recipes.git $WORKDIR/conda-recipes 
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       python $WORKDIR/conda-recipes/build_tools/conda_build_upload.py -w $WORKDIR -l $LAST_STABLE -B 0 -p cdms2 -r cdms -b $CIRCLE_BRANCH

  - &setup_run_tests
    name: setup_run_tests
    environment:
       PKGS: "testsrunner myproxyclient"
       CHANNELS: "-c cdat/label/nightly -c conda-forge"
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       conda create -y -n test_cdms --use-local $CHANNELS "$PY_VER" $PKGS
       conda activate test_cdms
       conda list
       echo "python -c 'import cdms2'"
       python -c "import cdms2"

  - &run_tests
    name: run_tests
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       # conda activate base
       conda activate test_cdms
       echo "python -c 'import cdms2'"
       python -c "import cdms2"
       python run_tests.py -H -v2 --subdir

jobs:
   macos_cdms_py2:
      macos:
         xcode: "11.1.0"
      environment:
         WORKDIR: "/Users/distiller/project/workdir"
         LAST_STABLE: "3.1.4"
         PY_VER: "python<3"
      steps:
         - checkout
         - run: *setup_miniconda
         - run: *build_cdms
         - run: *setup_run_tests
         - run: *run_tests

