version: 2.1

executors:
  linux:
    machine:
      image: circleci/classic:latest
  macos:
    macos:
      xcode: "11.4.0"

jobs:
  prep_host:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    environment:
      OS: << parameters.os >>
    steps:
      - run:
          command: |
            pwd

            echo "${OS}" >> test_os

            ls -la .

  build:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    environment:
      OS: << parameters.os >>
    steps:
      - run:
          command: |
            pwd

            echo "${OS}" >> test_os

            ls -la .

            cat test_os

workflows:
  cdms:
    jobs:
      - prep_host:
          matrix:
            parameters:
              os: [ linux, macos ]
          name: prep-host-<< matrix.os >>
      - prep_host:
          matrix:
            parameters:
              os: [ linux, macos ]
          name: prep-host-<< matrix.os >>
          requires:
            - prep-host-<< matrix.os >>
