version: 2.1

aliases:
  - &setup_miniconda
    name: setup_miniconda
    command: |
      MINICONDA_DIR=${CIRCLE_WORKING_DIRECTORY}/miniconda

      if [[ `uname` == "Darwin" ]]
      then
        curl -L -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
      else
        curl -L -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
      fi

      chmod +x miniconda.sh

      ./miniconda.sh -b -p ${MINICONDA_DIR}

      ls -la ${MINICODNA_DIR}

      source ${MINICONDA_DIR}/etc/profile.d/conda.sh

      conda activate base

      conda info

executors:
  linux:
    machine:
      image: circleci/classic:latest
  macos:
    macos:
      xcode: "11.4.0"

jobs:
  prep_host:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - attach_workspace:
          at: .
      - checkout:
          path: cdms
      - run: *setup_miniconda

workflows:
  cdms:
    jobs:
      - prep_host:
          matrix:
            parameters:
              os: [ linux, macos ]
          name: os-<< matrix.os >>
