version: 2

aliases:
  - &setup_miniconda
    name: setup_miniconda
    command: |
       mkdir -p workspace
       git clone -b validateNightly git@github.com:CDAT/cdat workspace/cdat
       # install_miniconda.py installs miniconda3 under $WORKDIR/miniconda
       python workspace/cdat/scripts/install_miniconda.py -w $WORKDIR -p 'py3'

  - &conda_rerender
    name: conda_rerender
    command: |
       git clone -b conda_forge_pinning https://github.com/CDAT/conda-recipes.git $WORKDIR/conda-recipes 
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       BUILD_SCRIPT="$WORKDIR/conda-recipes/build_tools/conda_build.py"
       python $BUILD_SCRIPT -w $WORKDIR -l $LAST_STABLE -B 0 -p $PKG_NAME -r $REPO_NAME -b $CIRCLE_BRANCH --do_rerender
       ls -l $WORKDIR/cdms2-feedstock/.ci_support

  - &conda_build
    name: conda_build
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       python --version
       conda config --add channels conda-forge --force
       conda config --add channels cdat/label/nightly --force
       conda config --set channel_priority strict
       BUILD_SCRIPT="$WORKDIR/conda-recipes/build_tools/conda_build.py"
       python $BUILD_SCRIPT -w $WORKDIR -p $PKG_NAME -r $REPO_NAME --build_version $BUILD_VARIANT_VER --do_build

  - &setup_run_tests
    name: setup_run_tests
    environment:
       PKGS: "testsrunner pytest myproxyclient"
       CHANNELS: "-c cdat/label/nightly -c conda-forge"
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       conda create -y -n test_cdms --use-local $CHANNELS "$CONDA_PY_VER" $PKG_NAME $PKGS $COVERAGE_PKGS
       conda activate test_cdms
       conda list
       conda list --verbose cdms2

  - &run_tests
    name: run_tests
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate test_cdms
       python run_tests.py -H -v2 --subdir $COVERAGE
       python run_tests.py -H -v2 --subdir -n 1 --dask

  - &conda_upload
    name: conda_upload
    command: |
       #if [[ $CIRCLE_BRANCH != "master" ]]; then
       #   exit 0
       #fi
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       UPLOAD_OPTIONS="-t $CONDA_UPLOAD_TOKEN upload -u $USER -l $LABEL"
       anaconda $UPLOAD_OPTIONS linux_build/miniconda/conda-bld/linux-64/$PKG_NAME-$VERSION.`date +%Y*`0.tar.bz2 --force
       anaconda $UPLOAD_OPTIONS macos_build/miniconda/conda-bld/osx-64/$PKG_NAME-$VERSION.`date +%Y*`0.tar.bz2 --force

  - &run_coveralls
    name: run_coveralls
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate $ENV_NAME
       coveralls
       conda deactivate

jobs:
   macos_setup:
      macos:
         xcode: "11.3.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "cdms2"
         REPO_NAME: "cdms"
         LAST_STABLE: "3.1.4"
      steps:
         - checkout
         - run: *setup_miniconda
         - run: *conda_rerender
         - persist_to_workspace:
              root: .
              paths: 
                 - macos_build

   linux_setup:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "cdms2"
         REPO_NAME: "cdms"
         LAST_STABLE: "3.1.4"
      steps:
         - checkout
         - run: *setup_miniconda
         - run: *conda_rerender
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build

   macos_cdms_py2:
      macos:
         xcode: "11.3.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "cdms2"
         REPO_NAME: "cdms"
         ENV_NAME: "test_cdms"
         LAST_STABLE: "3.1.4"
         CONDA_PY_VER: "python<3"
         BUILD_VARIANT_VER: "2.7"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - run: *setup_run_tests
         - run: *run_tests
         - store_artifacts:
              path: tests_html
              destination: tests_html
         - store_artifacts:
             path: tests_png
             destination: tests_png
         - persist_to_workspace:
              root: .
              paths:
                 - macos_build/miniconda/conda-bld/osx-64/cdms*tar.bz2

   macos_cdms_py37:
      macos:
         xcode: "11.3.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "cdms2"
         REPO_NAME: "cdms"
         ENV_NAME: "test_cdms"
         LAST_STABLE: "3.1.4"
         CONDA_PY_VER: "python>=3.7,<3.8"
         BUILD_VARIANT_VER: "3.7"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - run: *setup_run_tests
         - run: *run_tests
         - store_artifacts:
              path: tests_html
              destination: tests_html
         - store_artifacts:
             path: tests_png
             destination: tests_png
         - persist_to_workspace:
              root: .
              paths:
                 - macos_build/miniconda/conda-bld/osx-64/cdms*tar.bz2

   macos_cdms_py38:
      macos:
         xcode: "11.3.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "cdms2"
         REPO_NAME: "cdms"
         ENV_NAME: "test_cdms"
         LAST_STABLE: "3.1.4"
         CONDA_PY_VER: "python>=3.8,<3.9"
         BUILD_VARIANT_VER: "3.8"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - run: *setup_run_tests
         - run: *run_tests
         - store_artifacts:
              path: tests_html
              destination: tests_html
         - store_artifacts:
             path: tests_png
             destination: tests_png
         - persist_to_workspace:
              root: .
              paths:
                 - macos_build/miniconda/conda-bld/osx-64/cdms*tar.bz2

   linux_cdms_py2:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "cdms2"
         REPO_NAME: "cdms"
         ENV_NAME: "test_cdms"
         LAST_STABLE: "3.1.4"
         CONDA_PY_VER: "python<3"
         BUILD_VARIANT_VER: "2.7"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - run: *setup_run_tests
         - run: *run_tests
         - store_artifacts:
              path: tests_html
              destination: tests_html
         - store_artifacts:
             path: tests_png
             destination: tests_png
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build/miniconda/conda-bld/linux-64/cdms*tar.bz2

   linux_cdms_py37:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "cdms2"
         REPO_NAME: "cdms"
         ENV_NAME: "test_cdms"
         LAST_STABLE: "3.1.4"
         CONDA_PY_VER: "python>=3.7,<3.8"
         BUILD_VARIANT_VER: "3.7"
         #COVERAGE: "-c /home/circleci/project/tests/coverage.json"
         #COVERAGE_PKGS: "coverage coveralls"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - run: *setup_run_tests
         - run: *run_tests
         #- run: *run_coveralls
         - store_artifacts:
              path: tests_html
              destination: tests_html
         - store_artifacts:
             path: tests_png
             destination: tests_png
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build/miniconda/conda-bld/linux-64/cdms*tar.bz2

   linux_cdms_py38:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "cdms2"
         REPO_NAME: "cdms"
         ENV_NAME: "test_cdms"
         LAST_STABLE: "3.1.4"
         CONDA_PY_VER: "python>=3.8,<3.9"
         BUILD_VARIANT_VER: "3.8"
         #COVERAGE: "-c /home/circleci/project/tests/coverage.json"
         #COVERAGE_PKGS: "coverage coveralls"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - run: *setup_run_tests
         - run: *run_tests
         #- run: *run_coveralls
         - store_artifacts:
              path: tests_html
              destination: tests_html
         - store_artifacts:
             path: tests_png
             destination: tests_png
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build/miniconda/conda-bld/linux-64/cdms*tar.bz2

   upload:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "cdms2"
         VERSION: "3.1.4"
         USER: "cdat"
         #LABEL: "nightly"
         LABEL: "abort6"
      steps:
         - attach_workspace:
              at: .
         - run: pwd
         - run: *conda_upload

workflows:
   version: 2
   cdms:
      jobs:
         - macos_setup
         - linux_setup
         - macos_cdms_py2:
              requires:
                 - macos_setup
         - macos_cdms_py37:
              requires:
                 - macos_setup
         - macos_cdms_py38:
              requires:
                 - macos_setup
         - linux_cdms_py2:
              requires:
                 - linux_setup
         - linux_cdms_py37:
              requires:
                 - linux_setup
         - linux_cdms_py38:
              requires:
                 - linux_setup
         - upload:
              requires:
                 - macos_cdms_py2
                 - macos_cdms_py37
                 - macos_cdms_py38
                 - linux_cdms_py2
                 - linux_cdms_py37
                 - linux_cdms_py38
