name: Build workflow

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test_package:
    name: Test CDMS2 package
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 1
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('test-environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: test
          environment-file: test-environment.yml
          python-version: 3.6
          auto-activate-base: false
          miniforge-variant: Mambaforge
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: conda info
        run: |
          conda info
          conda list

      - name: install package
        run: |
          python setup.py install

      - name: run tests
        run: |
          python run_tests.py -v 2 -n 1
