on:
  pull_request:
    branches:
      - master

jobs:
  setup_conda:
    name: Build conda package
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('test-environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: test
          environment-file: test-environment.yml
          python-version: 3.6
          auto-activate-base: false
          miniforge-variant: Mambaforge

      - name: conda info
        run: |
          conda info
          conda list

      - name: install package
        run: |
          python setup.py install

          python -c "import cdms2"
